version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: vc-api
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
    networks:
      main:

networks:
  main:

volumes:
  dev-postgres-data:
