name: Test

on:
  push:

jobs:
  build-and-test:
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: user-test
          POSTGRES_DB: dev-test
          POSTGRES_PASSWORD: password-test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'

      - name: Rush install
        run: node common/scripts/install-run-rush.js install

      - name: Rush build
        run: node common/scripts/install-run-rush.js build --verbose

      - name: Run test
        env:
          CI: true
          NESTJS_PORT: 3000
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: user-test
          DB_PASSWORD: password-test
          DB_NAME: dev-test
        run: node common/scripts/install-run-rush.js test --verbose
